language: node_js

node_js:
  - '7'

addons:
  apt:
    packages:
      - xvfb
      
before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sudo add-apt-repository -y ppa:moti-p/cc
  - sudo apt-get update
  - sudo apt-get -y --reinstall install imagemagick

install:
  - npm i

script:
  - npm run test:all

